name: Docker Build and Push

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Debug OIDC Claims
        shell: bash
        run: |
          RESPONSE=$(curl -sS \
            -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
            "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=sts.amazonaws.com")

          TOKEN=$(echo "$RESPONSE" | python3 -c "import sys,json; print(json.load(sys.stdin)['value'])")

          PAYLOAD=$(echo "$TOKEN" | cut -d '.' -f2)

          python3 - "$PAYLOAD" <<'PY'
          import sys, json, base64
          payload = sys.argv[1]
          payload += "=" * (-len(payload) % 4)
          claims = json.loads(base64.urlsafe_b64decode(payload))
          print("aud:", claims.get("aud"))
          print("sub:", claims.get("sub"))
          print("repository:", claims.get("repository"))
          print("ref:", claims.get("ref"))
          PY
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: arn:aws:iam::050451366580:role/GitHubActionsECRRole
          aws-region: ap-northeast-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: my-flask-app
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
      - name: Deploy to ECS Fargate
        run: |
          VPC_ID=$(aws ec2 describe-vpcs \
            --filters "Name=is-default,Values=true" \
            --query "Vpcs[0].VpcId" \
            --output text)

          SUBNET_ID=$(aws ec2 describe-subnets \
            --filters "Name=vpc-id,Values=$VPC_ID" \
            --query "Subnets[0].SubnetId" \
            --output text)

          SG_ID=$(aws ec2 describe-security-groups \
            --filters \
              "Name=vpc-id,Values=$VPC_ID" \
              "Name=group-name,Values=my-flask-fargate-sg" \
            --query "SecurityGroups[0].GroupId" \
            --output text)

          aws ecs run-task \
            --cluster my-flask-cluster \
            --launch-type FARGATE \
            --task-definition my-flask-task \
            --count 1 \
            --network-configuration "awsvpcConfiguration={subnets=[$SUBNET_ID],securityGroups=[$SG_ID],assignPublicIp=ENABLED}"
